name: Lint Commits

on:
  push:
    branches: [main]
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run commitlint on last 10 commits
        run: npx commitlint --from=HEAD~10 --to=HEAD --verbose